name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: wget_vulkan
      run: wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
    
    - name: apt-update
      run: sudo apt-get update
      
    - name: apt-vulkan
      run: sudo apt install vulkan-sdk

    - name: install_xrandr
      run: sudo apt install libxrandr-dev

    - name: apt
      run: sudo apt-get install mesa-common-dev libglx-dev libxcursor-dev mesa-vulkan-drivers
    - name: make
      run: make